package lottery

import (
	"errors"
	"os"
	"testing"
)

// TestQRDecoderRoundTrip generates QR images with gozxing's writer and verifies
// that our decoder reads them back. The testdata images are generated by
// scripts/genqr (run `go run ./scripts/genqr` to regenerate).
func TestQRDecoderRoundTrip(t *testing.T) {
	d := &QRDecoder{}

	validCases := []struct {
		file string
		want string
	}{
		{"../../testdata/lottery_qr.png", "05,12,18,23,35,01,08"},
		{"../../testdata/lottery_qr_5plus1.png", "05 12 18 23 35 + 01 09"},
		{"../../testdata/lottery_qr_3plus1.png", "05,12,18,20,30,01,09"},
		{"../../testdata/lottery_qr_noprize.png", "05,12,20,30,32,09,10"},
	}
	for _, c := range validCases {
		data, err := os.ReadFile(c.file)
		if err != nil {
			t.Fatalf("read %s: %v", c.file, err)
		}
		got, err := d.Decode(data)
		if err != nil {
			t.Errorf("Decode(%s) error: %v", c.file, err)
			continue
		}
		if got != c.want {
			t.Errorf("Decode(%s) = %q, want %q", c.file, got, c.want)
		}
	}
}

func TestQRScanTicket(t *testing.T) {
	d := &QRDecoder{}

	// Valid ticket.
	data, err := os.ReadFile("../../testdata/lottery_qr.png")
	if err != nil {
		t.Fatal(err)
	}
	tk, err := d.ScanTicket(data)
	if err != nil {
		t.Fatalf("ScanTicket error: %v", err)
	}
	if len(tk.Front) != 5 || tk.Front[0] != 5 || tk.Front[4] != 35 {
		t.Errorf("unexpected front: %v", tk.Front)
	}
	if len(tk.Back) != 2 || tk.Back[0] != 1 || tk.Back[1] != 8 {
		t.Errorf("unexpected back: %v", tk.Back)
	}

	// Invalid payload (no numbers) must error.
	badData, err := os.ReadFile("../../testdata/lottery_qr_invalid.png")
	if err != nil {
		t.Fatal(err)
	}
	if _, err := d.ScanTicket(badData); err == nil {
		t.Error("expected error for invalid QR payload, got nil")
	}

	// Real ticket QR payload is a link -> ErrQRContainsLink (not a parse error).
	linkData, err := os.ReadFile("../../testdata/lottery_qr_link.png")
	if err != nil {
		t.Fatal(err)
	}
	if _, err := d.ScanTicket(linkData); !errors.Is(err, ErrQRContainsLink) {
		t.Errorf("link QR error = %v, want ErrQRContainsLink", err)
	}
	if _, err := d.Decode(linkData); err != nil {
		t.Errorf("Decode of link QR failed: %v", err)
	} else if !IsURL("https://s.sporttery.cn/HD/wyWLPG") || IsURL("05,12,18") {
		t.Error("IsURL misclassified payloads")
	}

	// Non-image bytes must error.
	if _, err := d.Decode([]byte("not an image")); err == nil {
		t.Error("expected error for non-image bytes, got nil")
	}
}

func TestScanTicketVerifyIntegration(t *testing.T) {
	d := &QRDecoder{}
	data, err := os.ReadFile("../../testdata/lottery_qr_5plus1.png")
	if err != nil {
		t.Fatal(err)
	}
	tk, err := d.ScanTicket(data)
	if err != nil {
		t.Fatal(err)
	}
	res, err := tk.Verify("05,12,18,23,35", "01,09")
	if err != nil {
		t.Fatal(err)
	}
	if !res.Won || res.Prize == nil || res.Prize.Tier != 1 {
		t.Errorf("expected 一等奖 (5+2), got %+v", res)
	}
}
