// Package mysqlutil contains small helpers shared by the user and role MySQL
// stores (currently the ID-type migration from CHAR(32) to BIGINT).
package mysqlutil

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
)

// migratableColumns lists, per table, the columns that survive into the
// bigint-ID schema, in insert order. The id column is intentionally excluded:
// it is regenerated by auto-increment.
var migratableColumns = map[string][]string{
	"users": {"username", "email", "password_hash", "nickname", "role", "mfa_secret", "created_at", "updated_at"},
	"roles": {"role_key", "name", "description", "builtin", "created_at", "updated_at"},
}

// columnDefaults supplies a value for columns that may be absent from a very
// old table, so the migration SELECT stays valid.
var columnDefaults = map[string]string{
	"email":      "NULL",
	"mfa_secret": "''",
}

// MigrateIDToBigInt rebuilds table when its id column is not BIGINT (the
// pre-bigint schema used CHAR(32) hex IDs). It reads every row (injecting
// defaults for columns missing from very old tables), drops the old table, and
// returns the rows so the caller can re-insert them after recreating the table
// with the new schema. A nil, nil return means no migration was needed.
func MigrateIDToBigInt(ctx context.Context, db *sql.DB, table string) ([][]any, error) {
	cols, ok := migratableColumns[table]
	if !ok {
		return nil, fmt.Errorf("migrateIDToBigInt: unsupported table %q", table)
	}
	exists, dataType, err := idColumnType(ctx, db, table)
	if err != nil {
		return nil, err
	}
	if !exists || strings.EqualFold(dataType, "bigint") {
		return nil, nil
	}
	present, err := existingColumns(ctx, db, table)
	if err != nil {
		return nil, err
	}

	// Build a SELECT that substitutes defaults for columns that predate them.
	exprs := make([]string, len(cols))
	for i, c := range cols {
		if present[c] {
			exprs[i] = c
			continue
		}
		def, ok := columnDefaults[c]
		if !ok {
			return nil, fmt.Errorf("migrate %s: required column %q missing", table, c)
		}
		exprs[i] = def + " AS " + c
	}

	rows, err := db.QueryContext(ctx, "SELECT "+strings.Join(exprs, ", ")+" FROM "+table+" ORDER BY created_at ASC")
	if err != nil {
		return nil, fmt.Errorf("read old %s rows: %w", table, err)
	}
	var oldRows [][]any
	for rows.Next() {
		vals := make([]any, len(cols))
		ptrs := make([]any, len(cols))
		for i := range vals {
			ptrs[i] = &vals[i]
		}
		if err := rows.Scan(ptrs...); err != nil {
			rows.Close()
			return nil, fmt.Errorf("scan old %s row: %w", table, err)
		}
		oldRows = append(oldRows, vals)
	}
	rows.Close()
	if err := rows.Err(); err != nil {
		return nil, err
	}

	// Drop the old table; the caller recreates it with the new schema.
	if _, err := db.ExecContext(ctx, "DROP TABLE IF EXISTS "+table); err != nil {
		return nil, fmt.Errorf("drop old %s: %w", table, err)
	}
	return oldRows, nil
}

// ReinsertMigrated inserts rows captured by MigrateIDToBigInt back into the
// freshly recreated table. ID is omitted so auto-increment assigns fresh
// sequential IDs. Legacy NULLs are normalized to satisfy the new NOT NULL
// columns (email stays NULL so the unique index tolerates many empty emails).
func ReinsertMigrated(ctx context.Context, db *sql.DB, table string, oldRows [][]any) error {
	if len(oldRows) == 0 {
		return nil
	}
	cols, ok := migratableColumns[table]
	if !ok {
		return fmt.Errorf("reinsertMigrated: unsupported table %q", table)
	}
	placeholders := strings.TrimSuffix(strings.Repeat("?, ", len(cols)), ", ")
	stmt := "INSERT INTO " + table + " (" + strings.Join(cols, ", ") + ") VALUES (" + placeholders + ")"
	for _, vals := range oldRows {
		args := make([]any, len(vals))
		copy(args, vals)
		for i, c := range cols {
			switch {
			case c == "email":
				// Empty/NULL email must stay NULL (unique index tolerates many).
				if s, ok := args[i].(string); ok && s == "" {
					args[i] = nil
				}
			case args[i] == nil && c == "builtin":
				args[i] = false
			case args[i] == nil:
				// All remaining migrated columns are NOT NULL text columns.
				args[i] = ""
			}
		}
		if _, err := db.ExecContext(ctx, stmt, args...); err != nil {
			return fmt.Errorf("reinsert migrated %s row: %w", table, err)
		}
	}
	return nil
}

// idColumnType returns whether the table exists and the DATA_TYPE of its id
// column (empty if the column is absent).
func idColumnType(ctx context.Context, db *sql.DB, table string) (bool, string, error) {
	var dataType string
	err := db.QueryRowContext(ctx,
		"SELECT DATA_TYPE FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = ? AND COLUMN_NAME = 'id'",
		table).Scan(&dataType)
	if err == sql.ErrNoRows {
		return false, "", nil
	}
	if err != nil {
		return false, "", fmt.Errorf("inspect %s.id type: %w", table, err)
	}
	return true, dataType, nil
}

// existingColumns returns the set of column names present in table.
func existingColumns(ctx context.Context, db *sql.DB, table string) (map[string]bool, error) {
	rows, err := db.QueryContext(ctx,
		"SELECT COLUMN_NAME FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = ?",
		table)
	if err != nil {
		return nil, fmt.Errorf("list %s columns: %w", table, err)
	}
	defer rows.Close()
	out := map[string]bool{}
	for rows.Next() {
		var c string
		if err := rows.Scan(&c); err != nil {
			return nil, err
		}
		out[c] = true
	}
	return out, rows.Err()
}
