// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "wechatapp-web",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "description": "Authenticates with username/password and returns a JWT to be\nsent as \"Authorization: Bearer \u003ctoken\u003e\".",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Login and get a JWT",
                "parameters": [
                    {
                        "description": "Username and password",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "JWT and user info",
                        "schema": {
                            "$ref": "#/definitions/handler.LoginResponse"
                        }
                    },
                    "400": {
                        "description": "Missing fields",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Wrong username or password",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/logout": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Revokes the presented JWT so it can no longer be used.",
                "tags": [
                    "auth"
                ],
                "summary": "Logout (revoke current token)",
                "responses": {
                    "200": {
                        "description": "message: 已退出登录",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Missing or invalid token",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/me": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns the profile of the authenticated user.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Get current user profile",
                "responses": {
                    "200": {
                        "description": "Current user profile",
                        "schema": {
                            "$ref": "#/definitions/user.SafeUser"
                        }
                    },
                    "401": {
                        "description": "Missing or invalid token",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "User no longer exists",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Deletes the authenticated user's own account after verifying\nthe password, and revokes the current token. The last admin\ncannot be deleted this way.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Delete my own account (注销账号)",
                "parameters": [
                    {
                        "description": "Password confirmation",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.DeleteMeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "message: 账号已注销",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Wrong password, or last admin cannot be deleted",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Missing or invalid token",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "User no longer exists",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/mfa": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Turns off two-factor authentication after verifying the\naccount password and a current TOTP code.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mfa"
                ],
                "summary": "Disable MFA",
                "parameters": [
                    {
                        "description": "Password and current code",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.MFADisableRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "message: 两步验证已关闭",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Wrong password or code",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Not authenticated",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/mfa/enable": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Verifies the submitted code against the setup secret and\nstores it, turning on two-factor authentication.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mfa"
                ],
                "summary": "Confirm and enable MFA",
                "parameters": [
                    {
                        "description": "Secret from setup and a current code",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.MFAEnableRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "MFA enabled",
                        "schema": {
                            "$ref": "#/definitions/handler.MFAEnableResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid secret or code",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Not authenticated",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/mfa/reset/confirm": {
            "post": {
                "description": "Verifies the emailed code and disables two-factor\nauthentication so the user can log in again with just their\npassword and re-enroll a fresh authenticator.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mfa"
                ],
                "summary": "Confirm an MFA reset with the emailed code",
                "parameters": [
                    {
                        "description": "Email and emailed code",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.MFAResetConfirmRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "message: 两步验证已重置",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Wrong/expired code or MFA not enabled",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "User not found",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/mfa/reset/request": {
            "post": {
                "description": "When a user lost their authenticator, this sends a 6-digit\nverification code to the account email. Requires the account\npassword. The response is generic to avoid account enumeration.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mfa"
                ],
                "summary": "Send an MFA reset code by email",
                "parameters": [
                    {
                        "description": "Email and password",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.MFAResetRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Generic success message",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Invalid body",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/mfa/setup": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Generates a TOTP secret and provisioning URI/QR code. Nothing\nis persisted until /auth/mfa/enable confirms a valid code.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mfa"
                ],
                "summary": "Begin MFA setup (生成 TOTP 密钥)",
                "responses": {
                    "200": {
                        "description": "Secret, otpauth URL and QR code",
                        "schema": {
                            "$ref": "#/definitions/handler.MFASetupResponse"
                        }
                    },
                    "400": {
                        "description": "MFA already enabled",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Not authenticated",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/mfa/verify": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Exchanges the short-lived mfa_token returned by /auth/login\nplus a TOTP code for a full access token.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mfa"
                ],
                "summary": "Complete login with the second factor",
                "parameters": [
                    {
                        "description": "TOTP code",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.MFAVerifyRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Full access token",
                        "schema": {
                            "$ref": "#/definitions/handler.LoginResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid code",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Missing/invalid/expired MFA challenge token",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/password": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Changes the password of the authenticated user after verifying the old one.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Change own password",
                "parameters": [
                    {
                        "description": "Old and new password",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.ChangePasswordRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "message: 密码修改成功",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Invalid input or wrong old password",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Missing or invalid token",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "User no longer exists",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "description": "Creates a normal (user-role) account. Login afterwards to get a token.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Register a new user",
                "parameters": [
                    {
                        "description": "Username, password and optional nickname",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created user",
                        "schema": {
                            "$ref": "#/definitions/user.SafeUser"
                        }
                    },
                    "400": {
                        "description": "Invalid input",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Username already exists",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/lottery/parse-ticket": {
            "post": {
                "description": "Validates client-supplied ticket numbers (from manual input or\non-device OCR) and returns them normalized, so the app can show\na confirmation screen before calling /lottery/verify-ticket.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "lottery"
                ],
                "summary": "Parse and normalize 大乐透 ticket numbers",
                "parameters": [
                    {
                        "description": "Ticket numbers as bets or text",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.TicketInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Normalized issue and bets",
                        "schema": {
                            "$ref": "#/definitions/handler.ParseTicketResponse"
                        }
                    },
                    "400": {
                        "description": "Missing input or invalid numbers (message names the offending bet/line)",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/lottery/scan": {
            "post": {
                "description": "Decodes a QR-code image and extracts the 大乐透 numbers printed\nby the user (5 front numbers + 2 back numbers). The QR payload\nmust contain 7 numbers, e.g. \"05,12,18,23,35,01,08\".",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "lottery"
                ],
                "summary": "Recognize 大乐透 numbers from a QR code",
                "parameters": [
                    {
                        "type": "file",
                        "description": "QR code image containing the ticket numbers",
                        "name": "qrcode",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Decoded raw text and recognized numbers",
                        "schema": {
                            "$ref": "#/definitions/handler.ScanResponse"
                        }
                    },
                    "400": {
                        "description": "Missing qrcode, unreadable image, or unparseable numbers",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Image decodes but contains no valid QR code",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/lottery/verify": {
            "post": {
                "description": "Scans the QR code to get the user's printed numbers, then\ncompares them with the given winning numbers and returns the\nprize tier if the ticket wins.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "lottery"
                ],
                "summary": "Verify a 大乐透 ticket against winning numbers",
                "parameters": [
                    {
                        "type": "file",
                        "description": "QR code image with the user's printed numbers",
                        "name": "qrcode",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Winning front-area numbers, e.g. 05,12,18,23,35",
                        "name": "winning_front",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Winning back-area numbers, e.g. 01,08",
                        "name": "winning_back",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Match counts and prize (won=false if no prize)",
                        "schema": {
                            "$ref": "#/definitions/lottery.VerifyResult"
                        }
                    },
                    "400": {
                        "description": "Missing fields or invalid numbers",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Image decodes but contains no valid QR code",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/lottery/verify-ticket": {
            "post": {
                "description": "Verifies a printed 大乐透 ticket that may contain several bets\n(单式票通常 5 注). Numbers may be sent as structured bets or as\nmulti-line text. Winning numbers can be supplied directly; if\nomitted and an issue is given, they are fetched from the\nofficial China Sports Lottery draw-history API.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "lottery"
                ],
                "summary": "Verify a multi-bet 大乐透 ticket",
                "parameters": [
                    {
                        "description": "Ticket bets and optional winning numbers",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.VerifyTicketRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Per-bet match counts, prize and totals",
                        "schema": {
                            "$ref": "#/definitions/lottery.TicketVerifyResult"
                        }
                    },
                    "400": {
                        "description": "Invalid numbers or missing winning numbers/issue",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "502": {
                        "description": "Failed to fetch official winning numbers",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/lottery/winning/{issue}": {
            "get": {
                "description": "Fetches the official draw result for the given issue from the\nChina Sports Lottery API (cached in memory).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "lottery"
                ],
                "summary": "Get official 大乐透 winning numbers",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Issue number, e.g. 26102",
                        "name": "issue",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Official draw result",
                        "schema": {
                            "$ref": "#/definitions/lottery.WinningNumbers"
                        }
                    },
                    "404": {
                        "description": "Issue not found",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "502": {
                        "description": "Upstream API error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/replace-background": {
            "post": {
                "description": "Uploads an image, removes its background with the remove.bg API,\nthen optionally replaces the background with a solid color or another\nimage. Returns the processed image directly as the response body.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "image/png",
                    "image/jpeg"
                ],
                "tags": [
                    "background"
                ],
                "summary": "Replace image background",
                "parameters": [
                    {
                        "type": "file",
                        "description": "Source image whose background will be removed",
                        "name": "image",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "Background image to place behind the cutout (wins over color)",
                        "name": "background",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Hex background color, e.g. #00aaff or #fff",
                        "name": "color",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "default": "auto",
                        "description": "remove.bg size parameter",
                        "name": "size",
                        "in": "formData"
                    },
                    {
                        "enum": [
                            "png",
                            "jpeg"
                        ],
                        "type": "string",
                        "default": "png",
                        "description": "Output image format",
                        "name": "format",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Processed image (PNG or JPEG)",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "400": {
                        "description": "Bad request: missing image, unreadable file, or invalid color",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal error while composing the result",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "502": {
                        "description": "remove.bg upstream API error (e.g. invalid API key)",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/users": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns all accounts. Admin only.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "List all users (admin)",
                "responses": {
                    "200": {
                        "description": "User list",
                        "schema": {
                            "$ref": "#/definitions/handler.UserListResponse"
                        }
                    },
                    "401": {
                        "description": "Not authenticated",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Not an admin",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Creates an account with an explicit role. Admin only.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Create a user (admin)",
                "parameters": [
                    {
                        "description": "New account",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.CreateUserRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created user",
                        "schema": {
                            "$ref": "#/definitions/user.SafeUser"
                        }
                    },
                    "400": {
                        "description": "Invalid input",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Not authenticated",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Not an admin",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Username already exists",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/users/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns one account. Admin, or the user themselves.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Get user detail",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "User detail",
                        "schema": {
                            "$ref": "#/definitions/user.SafeUser"
                        }
                    },
                    "401": {
                        "description": "Not authenticated",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Not allowed to view this user",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "User not found",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Updates nickname (self or admin) and role (admin only).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Update a user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Fields to update",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.UpdateUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Updated user",
                        "schema": {
                            "$ref": "#/definitions/user.SafeUser"
                        }
                    },
                    "400": {
                        "description": "Invalid input",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Not authenticated",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Not allowed to edit this user",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "User not found",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Removes an account. Admin only.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Delete a user (admin)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "message: 用户已删除",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Not authenticated",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Not an admin",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "User not found",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/users/{id}/mfa": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Disables two-factor authentication for another account, for\nexample when the user lost their authenticator. Admin only.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Reset a user's MFA (admin)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "message: 已重置该用户的两步验证",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Not authenticated",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Not an admin",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "User not found",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handler.BetInput": {
            "type": "object",
            "properties": {
                "back": {
                    "description": "后区 2 个号码",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    },
                    "example": [
                        10,
                        12
                    ]
                },
                "front": {
                    "description": "前区 5 个号码",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    },
                    "example": [
                        4,
                        10,
                        12,
                        16,
                        20
                    ]
                }
            }
        },
        "handler.ChangePasswordRequest": {
            "type": "object",
            "required": [
                "new_password",
                "old_password"
            ],
            "properties": {
                "new_password": {
                    "description": "新密码（至少6位）",
                    "type": "string",
                    "example": "new123456"
                },
                "old_password": {
                    "description": "原密码",
                    "type": "string",
                    "example": "old123456"
                }
            }
        },
        "handler.CreateUserRequest": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "email": {
                    "description": "邮箱（推荐填写，用于两步验证重置）",
                    "type": "string",
                    "example": "lisi@example.com"
                },
                "nickname": {
                    "description": "昵称",
                    "type": "string",
                    "example": "李四"
                },
                "password": {
                    "description": "密码（至少6位）",
                    "type": "string",
                    "example": "secret123"
                },
                "role": {
                    "description": "角色：user | admin（默认 user）",
                    "type": "string",
                    "enum": [
                        "user",
                        "admin"
                    ],
                    "example": "user"
                },
                "username": {
                    "description": "用户名",
                    "type": "string",
                    "example": "lisi"
                }
            }
        },
        "handler.DeleteMeRequest": {
            "type": "object",
            "required": [
                "password"
            ],
            "properties": {
                "password": {
                    "description": "当前密码确认",
                    "type": "string",
                    "example": "secret123"
                }
            }
        },
        "handler.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "failed to read uploaded image: ..."
                }
            }
        },
        "handler.LoginRequest": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "description": "密码",
                    "type": "string",
                    "example": "admin123"
                },
                "username": {
                    "description": "用户名",
                    "type": "string",
                    "example": "admin"
                }
            }
        },
        "handler.LoginResponse": {
            "type": "object",
            "properties": {
                "expires_at": {
                    "description": "过期时间（access 或 mfa_token 的）",
                    "type": "string"
                },
                "mfa_required": {
                    "description": "MFARequired 为 true 时，需带上 mfa_token 调用 POST /auth/mfa/verify 完成登录。",
                    "type": "boolean"
                },
                "mfa_token": {
                    "description": "MFAToken 是第二步验证用的短期令牌（5 分钟，一次性）。",
                    "type": "string"
                },
                "token": {
                    "description": "JWT（放在 Authorization: Bearer \u003ctoken\u003e 头中）",
                    "type": "string"
                },
                "token_type": {
                    "description": "恒为 Bearer",
                    "type": "string"
                },
                "user": {
                    "description": "用户信息（需要 MFA 第二步时不返回）",
                    "allOf": [
                        {
                            "$ref": "#/definitions/user.SafeUser"
                        }
                    ]
                }
            }
        },
        "handler.MFADisableRequest": {
            "type": "object",
            "required": [
                "code",
                "password"
            ],
            "properties": {
                "code": {
                    "description": "当前验证码",
                    "type": "string",
                    "example": "123456"
                },
                "password": {
                    "description": "当前密码",
                    "type": "string",
                    "example": "secret123"
                }
            }
        },
        "handler.MFAEnableRequest": {
            "type": "object",
            "required": [
                "code",
                "secret"
            ],
            "properties": {
                "code": {
                    "description": "认证器 App 当前 6 位验证码",
                    "type": "string",
                    "example": "123456"
                },
                "secret": {
                    "description": "setup 返回的 secret",
                    "type": "string",
                    "example": "JBSWY3DPEHPK3PXP"
                }
            }
        },
        "handler.MFAEnableResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "description": "提示信息",
                    "type": "string"
                }
            }
        },
        "handler.MFAResetConfirmRequest": {
            "type": "object",
            "required": [
                "code",
                "email"
            ],
            "properties": {
                "code": {
                    "description": "邮箱收到的 6 位验证码",
                    "type": "string",
                    "example": "123456"
                },
                "email": {
                    "description": "账号绑定的邮箱",
                    "type": "string",
                    "example": "user@example.com"
                }
            }
        },
        "handler.MFAResetRequest": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "description": "账号绑定的邮箱",
                    "type": "string",
                    "example": "user@example.com"
                },
                "password": {
                    "description": "账号密码",
                    "type": "string",
                    "example": "secret123"
                }
            }
        },
        "handler.MFASetupResponse": {
            "type": "object",
            "properties": {
                "otpauth_url": {
                    "description": "otpauth:// URI，可自行生成二维码",
                    "type": "string"
                },
                "qr_code": {
                    "description": "data:image/png;base64,... 可直接放进 \u003cimg src\u003e",
                    "type": "string"
                },
                "secret": {
                    "description": "base32 密钥（手动输入时使用）",
                    "type": "string"
                }
            }
        },
        "handler.MFAVerifyRequest": {
            "type": "object",
            "required": [
                "code"
            ],
            "properties": {
                "code": {
                    "description": "认证器 App 当前 6 位验证码",
                    "type": "string",
                    "example": "123456"
                }
            }
        },
        "handler.ParseTicketResponse": {
            "type": "object",
            "properties": {
                "bets": {
                    "description": "规范化后的号码",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/lottery.SuperLotto"
                    }
                },
                "issue": {
                    "description": "识别出的期号",
                    "type": "string"
                },
                "total_bets": {
                    "description": "注数",
                    "type": "integer"
                }
            }
        },
        "handler.RegisterRequest": {
            "type": "object",
            "required": [
                "email",
                "password",
                "username"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "user@example.com"
                },
                "nickname": {
                    "description": "昵称（可选）",
                    "type": "string",
                    "example": "张三"
                },
                "password": {
                    "description": "密码（至少6位）",
                    "type": "string",
                    "example": "secret123"
                },
                "username": {
                    "description": "用户名（3-32位字母/数字/下划线）",
                    "type": "string",
                    "example": "zhangsan"
                }
            }
        },
        "handler.ScanResponse": {
            "type": "object",
            "properties": {
                "raw": {
                    "description": "QR 码解码出的原始文本",
                    "type": "string"
                },
                "ticket": {
                    "description": "识别出的号码",
                    "allOf": [
                        {
                            "$ref": "#/definitions/lottery.SuperLotto"
                        }
                    ]
                }
            }
        },
        "handler.TicketInput": {
            "type": "object",
            "properties": {
                "bets": {
                    "description": "票面号码；与 text 二选一",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handler.BetInput"
                    }
                },
                "issue": {
                    "description": "期号（可选）",
                    "type": "string",
                    "example": "26102"
                },
                "text": {
                    "description": "整票文本，一行一注；bets 为空时使用",
                    "type": "string"
                }
            }
        },
        "handler.UpdateUserRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "description": "邮箱（可选，本人或管理员可改）",
                    "type": "string",
                    "example": "zhangsan@example.com"
                },
                "nickname": {
                    "description": "昵称（可选）",
                    "type": "string",
                    "example": "张三"
                },
                "role": {
                    "description": "角色（仅管理员可改）",
                    "type": "string",
                    "enum": [
                        "user",
                        "admin"
                    ],
                    "example": "user"
                }
            }
        },
        "handler.UserListResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/user.SafeUser"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "handler.VerifyTicketRequest": {
            "type": "object",
            "properties": {
                "bets": {
                    "description": "票面号码；与 text 二选一",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handler.BetInput"
                    }
                },
                "issue": {
                    "description": "期号（可选）",
                    "type": "string",
                    "example": "26102"
                },
                "text": {
                    "description": "整票文本，一行一注；bets 为空时使用",
                    "type": "string"
                },
                "winning_back": {
                    "description": "开奖后区（可选）",
                    "type": "string",
                    "example": "06,07"
                },
                "winning_front": {
                    "description": "开奖前区（可选）",
                    "type": "string",
                    "example": "01,03,07,27,28"
                }
            }
        },
        "lottery.BetResult": {
            "type": "object",
            "properties": {
                "amount": {
                    "description": "按奖池档位算出的单注奖金",
                    "type": "string"
                },
                "back": {
                    "description": "后区号码",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "front": {
                    "description": "前区号码",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "index": {
                    "description": "注序号（从 1 开始）",
                    "type": "integer"
                },
                "matched_back": {
                    "description": "命中后区个数",
                    "type": "integer"
                },
                "matched_front": {
                    "description": "命中前区个数",
                    "type": "integer"
                },
                "prize": {
                    "$ref": "#/definitions/lottery.Prize"
                },
                "won": {
                    "description": "该注是否中奖",
                    "type": "boolean"
                }
            }
        },
        "lottery.Prize": {
            "type": "object",
            "properties": {
                "amount_above_8yi": {
                    "description": "奖池 8 亿以上单注奖金",
                    "type": "string"
                },
                "amount_below_8yi": {
                    "description": "奖池 8 亿以下单注奖金",
                    "type": "string"
                },
                "condition": {
                    "description": "中奖条件，如\"5+2\"",
                    "type": "string"
                },
                "tier": {
                    "description": "奖级（一等奖=1 … 七等奖=7）",
                    "type": "integer"
                },
                "tier_name": {
                    "description": "奖级名称，如\"一等奖\"",
                    "type": "string"
                }
            }
        },
        "lottery.SuperLotto": {
            "type": "object",
            "properties": {
                "back": {
                    "description": "后区号码",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    },
                    "example": [
                        1,
                        8
                    ]
                },
                "front": {
                    "description": "前区号码",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    },
                    "example": [
                        5,
                        12,
                        18,
                        23,
                        35
                    ]
                }
            }
        },
        "lottery.TicketVerifyResult": {
            "type": "object",
            "properties": {
                "bets": {
                    "description": "逐注结果",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/lottery.BetResult"
                    }
                },
                "issue": {
                    "description": "期号",
                    "type": "string"
                },
                "total_bets": {
                    "description": "总注数",
                    "type": "integer"
                },
                "total_won": {
                    "description": "是否至少中一注",
                    "type": "boolean"
                },
                "winning": {
                    "description": "使用的开奖号码",
                    "allOf": [
                        {
                            "$ref": "#/definitions/lottery.WinningNumbers"
                        }
                    ]
                },
                "winning_bets": {
                    "description": "中奖注数",
                    "type": "integer"
                }
            }
        },
        "lottery.VerifyResult": {
            "type": "object",
            "properties": {
                "matched_back": {
                    "description": "命中后区个数",
                    "type": "integer"
                },
                "matched_front": {
                    "description": "命中前区个数",
                    "type": "integer"
                },
                "prize": {
                    "description": "中奖信息（未中奖时为 null）",
                    "allOf": [
                        {
                            "$ref": "#/definitions/lottery.Prize"
                        }
                    ]
                },
                "won": {
                    "description": "是否中奖",
                    "type": "boolean"
                }
            }
        },
        "lottery.WinningNumbers": {
            "type": "object",
            "properties": {
                "back": {
                    "description": "后区开奖号码",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    },
                    "example": [
                        6,
                        7
                    ]
                },
                "draw_time": {
                    "description": "开奖日期",
                    "type": "string",
                    "example": "2026-09-07"
                },
                "front": {
                    "description": "前区开奖号码",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    },
                    "example": [
                        1,
                        3,
                        7,
                        27,
                        28
                    ]
                },
                "issue": {
                    "description": "期号",
                    "type": "string",
                    "example": "26102"
                },
                "pool_above_8yi": {
                    "description": "奖池是否达到 8 亿",
                    "type": "boolean"
                },
                "pool_balance": {
                    "description": "开奖后奖池（元）",
                    "type": "number"
                }
            }
        },
        "user.SafeUser": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "mfa_enabled": {
                    "description": "是否已开启两步验证",
                    "type": "boolean"
                },
                "nickname": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "JWT issued by POST /auth/login, sent as \"Bearer \u003ctoken\u003e\"",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{"http"},
	Title:            "wechatapp-web API",
	Description:      "Image background replacement API. Uploads an image, removes its\nbackground via the remove.bg service, then optionally composites\nthe cutout onto a new background (solid color or another image).",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
