package router

import (
	"log"
	"net/http"

	"github.com/gin-gonic/gin"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"

	"wechatapp-web/internal/auth"
	"wechatapp-web/internal/config"
	"wechatapp-web/internal/handler"
	"wechatapp-web/internal/mail"
	"wechatapp-web/internal/user"
)

// New builds the gin engine with all routes registered.
func New(cfg *config.Config) *gin.Engine {
	r := gin.Default()

	// Health check.
	r.GET("/healthz", func(c *gin.Context) {
		c.JSON(http.StatusOK, gin.H{"status": "ok"})
	})

	// --- Authentication infrastructure -----------------------------------
	// The store lives for the whole process; the OS reclaims it on exit, so
	// it must NOT be closed here (router.New returns before the server runs).
	users := newUserStore(cfg)
	seedAdmin(users, cfg)
	jwtManager := auth.NewManager(cfg.JWTSecret, cfg.JWTTTL, cfg.JWTIssuer)

	mailer := mail.NewSender(mail.Config{
		Mode:     cfg.EmailMode,
		Host:     cfg.SMTPHost,
		Port:     cfg.SMTPPort,
		User:     cfg.SMTPUser,
		Password: cfg.SMTPPassword,
		From:     cfg.SMTPFrom,
	})
	emailOTP := auth.NewEmailOTPManager()

	authH := handler.NewAuthHandler(users, jwtManager, cfg.MFAIssuer, mailer, emailOTP)
	userH := handler.NewUserHandler(users)

	// API v1 routes.
	bg := handler.NewBackgroundHandler(cfg)
	lotto := handler.NewLotteryHandler(cfg)
	v1 := r.Group("/api/v1")
	{
		// Auth endpoints (public).
		v1.POST("/auth/register", authH.Register)
		v1.POST("/auth/login", authH.Login)
		// Auth endpoints (authenticated).
		authed := v1.Group("", jwtManager.RequireAuth())
		{
			authed.POST("/auth/logout", authH.Logout)
			authed.GET("/auth/me", authH.Me)
			authed.DELETE("/auth/me", authH.DeleteMe)
			authed.PUT("/auth/password", authH.ChangePassword)
			// MFA management (already authenticated with a full access token).
			authed.POST("/auth/mfa/setup", authH.MFASetup)
			authed.POST("/auth/mfa/enable", authH.MFAEnable)
			authed.DELETE("/auth/mfa", authH.MFADisable)
		}
		// Login step 2: accepts only the short-lived challenge token.
		v1.POST("/auth/mfa/verify", jwtManager.RequireMFAChallenge(), authH.MFAVerify)
		// MFA reset via email (public: the user is locked out of their account).
		v1.POST("/auth/mfa/reset/request", authH.MFAResetRequestCode)
		v1.POST("/auth/mfa/reset/confirm", authH.MFAResetConfirm)
		// User management (admin).
		admin := v1.Group("", jwtManager.RequireAuth(), auth.RequireRole(user.RoleAdmin))
		{
			admin.GET("/users", userH.List)
			admin.POST("/users", userH.Create)
			admin.DELETE("/users/:id", userH.Delete)
			admin.DELETE("/users/:id/mfa", userH.MFAResetByAdmin)
		}
		// User detail: admin or self (checked in handler).
		userDetail := v1.Group("", jwtManager.RequireAuth())
		{
			userDetail.GET("/users/:id", userH.Get)
			userDetail.PUT("/users/:id", userH.Update)
		}

		v1.POST("/replace-background", bg.ReplaceBackground)
		v1.POST("/lottery/scan", lotto.Scan)
		v1.POST("/lottery/verify", lotto.Verify)
		v1.POST("/lottery/parse-ticket", lotto.ParseTicket)
		v1.POST("/lottery/verify-ticket", lotto.VerifyTicket)
		v1.GET("/lottery/winning/:issue", lotto.Winning)
	}

	// Swagger UI at /swagger/index.html (docs generated by swag).
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	return r
}

// newUserStore picks the storage backend: MySQL when DB_HOST is configured,
// otherwise the in-memory store (optionally persisted to a JSON file).
func newUserStore(cfg *config.Config) user.Store {
	if cfg.DBHost != "" {
		mc := user.MySQLConfig{
			Host:     cfg.DBHost,
			Port:     cfg.DBPort,
			User:     cfg.DBUser,
			Password: cfg.DBPassword,
			DBName:   cfg.DBName,
			Charset:  cfg.DBCharset,
		}
		store, err := user.OpenMySQL(mc)
		if err != nil {
			log.Fatalf("failed to connect to MySQL: %v", err)
		}
		log.Printf("user store: MySQL (%s:%s/%s)", mc.Host, mc.Port, mc.DBName)
		return store
	}
	store := user.NewMemoryStore(cfg.UsersFile)
	if cfg.UsersFile != "" {
		log.Printf("user store: in-memory with JSON persistence (%s)", cfg.UsersFile)
	} else {
		log.Printf("user store: in-memory only (set DB_HOST or USERS_FILE for persistence)")
	}
	return store
}

// seedAdmin creates the initial admin account if it does not exist yet. It is
// idempotent, so the admin is restored whenever the store is empty/persisted.
func seedAdmin(users user.Store, cfg *config.Config) {
	if _, err := users.GetByUsername(cfg.AdminUsername); err == nil {
		return
	}
	hash, err := auth.HashPassword(cfg.AdminPassword)
	if err != nil {
		log.Printf("[warn] failed to hash admin password: %v", err)
		return
	}
	u := &user.User{
		ID:           user.NewID(),
		Username:     cfg.AdminUsername,
		PasswordHash: hash,
		Nickname:     "管理员",
		Role:         user.RoleAdmin,
	}
	if err := users.Create(u); err != nil {
		log.Printf("[warn] failed to seed admin user: %v", err)
		return
	}
	log.Printf("seeded admin user %q (change the default password after first login)", cfg.AdminUsername)
}
